#!/bin/bash

#
# d12-- prints a random number between 1-12
#

# worked on mac:
# RANDOM=$(date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s")

# worked on ubuntu:
RANDOM=$(od -A n -t d -N 1 /dev/urandom | tr -d ' ')

export d12=$(( $RANDOM % 12 + 1 ))

echo $d12
