#!/bin/bash

#
# d20-- prints a random number between 1-20
#

# worked on mac:
# RANDOM=$(date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s")

# worked on ubuntu:
RANDOM=$(od -A n -t d -N 1 /dev/urandom | tr -d ' ')

export d20=$(( $RANDOM % 20 + 1 ))

echo $d20
